skip_commits:
  files:
    - README.md

image: WMF 5

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

environment:
  NugetApiKey:
    secure: DIE2y66RzXWvp2Q0wIOLlBTjxILBGeHyyg3pjwWjdVrggzuj9BuMWCdfHFmt9nt2
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN

install:
- ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose

build_script:
  - cd build
  - ps: ./build.ps1
  
artifacts:
  - path: bin\*.nupkg
    name: Cake.Umbraco.PackageUploader

deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: Cake.Umbraco.PackageUploader
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: Cake.Umbraco.PackageUploader
    on:
      branch: master
      appveyor_repo_tag: true